Update ledger highlight queries
nvim-treesitter/nvim-treesitter pull request #1369
Opened 2021-06-07 21:59 UTC by cbarrete

2021-06-07 22:37 UTC, theHamsta approved these changes

2021-06-07 22:39 UTC, theHamsta commented
You have to update the lockfile when performing incompatible changes

2021-06-08 06:03 UTC, vigoux requested changes

2021-06-08 06:03 UTC, vigoux commented on queries/ledger/highlights.scm
> +((commodity) text.literal)
There's a missing `@` here.

2021-06-11 12:00 UTC, vigoux commented on queries/ledger/highlights.scm
> +((commodity) text.literal)
No worry pal, thanks for this contribution and for maintaining ledger !!

2021-06-11 12:00 UTC, vigoux approved these changes

2021-06-11 12:00 UTC, merged