Allow unused_identifier in function definitions in Elixir
nvim-treesitter/nvim-treesitter pull request #1477
Opened 2021-07-02 18:43 UTC by hauleth

2021-07-02 19:05 UTC, theHamsta approved these changes

2021-07-02 19:47 UTC, theHamsta commented on queries/elixir/highlights.scm
> +    (map) @comment
Why is map a comment?

2021-07-02 20:32 UTC, theHamsta requested changes
~~There are some queries without captures~~

2021-07-02 20:33 UTC, theHamsta approved these changes

2021-07-02 20:35 UTC, theHamsta commented
@nifoc could you have a look on this?

2021-07-02 20:41 UTC, nifoc commented
I think this was removed by accident (from `Definition with (some) arguments and guard(s)`):

```
(_
 (keyword_list (identifier) @parameter))
```

Otherwise LGMT ❤️

2021-07-06 17:43 UTC, theHamsta commented
@hauleth could you address the comment of @nifoc ?

2021-07-07 08:04 UTC, hauleth commented
@theHamsta yes, soonish

2021-07-13 15:23 UTC, hauleth commented
@theHamsta I just removed everything and allowed everything to be called in the parameters, as it is how Elixir works:

```elixir
def foo(bar(a: a)) do
  # …
end
```

Is completely valid code that can be spotted in real projects (when working with Erlang records).

2021-07-13 15:41 UTC, nifoc commented
Sadly this also removes all other `@parameter` highlights.

tree-sitter doesn't really support languages with pattern matching (in function heads) at the moment, which is why these queries are so *verbose* in the first place. Some patterns are explicitly listed in the query file to at least highlight the most common `@parameter`s in pattern matches.

Currently I would say it's nearly impossible to correctly highlight every possible pattern match ...
[This discussion](https://github.com/tree-sitter/tree-sitter/discussions/1096) also mentions the above issue and links to some further sources/issues.

2021-07-13 20:28 UTC, hauleth commented
@nifoc that discussion is pointless as even with such thing supporting all possible patterns as `quote` call can be used as a pattern. Also I think that *missing* feature is better than having feature that works only partially. That is why I think that just removing support for colouring `@parameter` and instead having full support for colouring function definitions is worth it.

And this is how it looks right now:

<img width="204" alt="Zrzut ekranu 2021-07-13 o 22 27 56" src="https://user-images.githubusercontent.com/291639/125520255-08e813c0-c6a0-4ea3-b12f-866c1be13457.png">

2021-07-13 20:44 UTC, nifoc commented
Okay, now I understand.

To add a catch all query that highlights the function name, but doesn't highlight parameters (because none of the more specific queries match), I would suggest adding the following before `; Definition with (some) arguments and (optional) defaults`:

```
(call (function_identifier) @keyword.function
 (call
  function: (function_identifier) @function)
 (#lua-match? @keyword.function "^def%a*$"))
```

This will match both `foo` (and mark them as `@function`):

<img width="1104" alt="Bildschirmfoto 2021-07-13 um 22 41 01" src="https://user-images.githubusercontent.com/222412/125522110-df27e469-7067-4746-bc62-3344985d5dd4.png">

2021-07-13 21:03 UTC, nifoc commented
Sorry if my previous comment caused any confusion. The solution could cause tree-sitter to run into an internal limit, which results in only some parameters being highlighted for functions with many parameters.

The following should match (and highlight) `foo` in both function definitions:
(Notice the `?` after the `(arguments ...)`)

```
; Definition with (some) arguments and (optional) defaults
(call (function_identifier) @keyword.function
 (call
  function: (function_identifier) @function
  (arguments
   [(identifier) @parameter
    (tuple (identifier) @parameter)
    (list (identifier) @parameter)
    (_
     (keyword_list (identifier) @parameter))
    (binary_op
     left: (identifier) @parameter
     operator: "\\\\")])?)
 (#lua-match? @keyword.function "^def%a*$"))

; Definition with (some) arguments and guard(s)
(call (function_identifier) @keyword.function
 (binary_op
  left:
   (call
    function: (function_identifier) @function
    (arguments
     [(identifier) @parameter
      (tuple (identifier) @parameter)
      (list (identifier) @parameter)
      (_
       (keyword_list (identifier) @parameter))])?)
  operator: "when")
 (#lua-match? @keyword.function "^def%a*$"))
```

Looks like this in the playground:

![Bildschirmfoto 2021-07-13 um 23 01 23](https://user-images.githubusercontent.com/222412/125524489-b3af7b41-c0fe-4794-8a26-f432599740f1.png)

2021-07-14 12:59 UTC, hauleth commented
However it will again not apply the `@parameter` to the passed arguments, yes? That was the core of the problem.

It seems that if you try to do almost any pattern matching in the function head, then it will fail. It seems that even the really basic pattern matching will make the parser to fail.

<img width="308" alt="Zrzut ekranu 2021-07-14 o 14 57 41" src="https://user-images.githubusercontent.com/291639/125625813-223b0caf-b3a6-4716-86ad-92b7c797d2c7.png">

2021-07-14 13:25 UTC, nifoc commented
> However it will again not apply the `@parameter` to the passed arguments, yes?

In most of your examples it will not highlight the `@parameter`.
(But with the `?` added it will at least highlight the `@function` in all cases)

<img width="289" alt="Bildschirmfoto 2021-07-14 um 15 22 23" src="https://user-images.githubusercontent.com/222412/125629292-992b16f0-5bb2-4d0b-b4dd-0de602d10fe5.png">

> That was the core of the problem.

Just so we're definitely talking about the same thing, can you maybe spell out what you wanted to achieve with this PR?
I was under the impression that it's mainly about the missing `@function` highlight.

2021-07-14 16:33 UTC, theHamsta commented
@nifoc I'm really not an elixir expert. Can you approve this as soon as the PR is ready? I have the feeling I'm not really helpful regarding elixir...

2021-07-18 16:44 UTC, merged

2021-07-18 17:20 UTC, nifoc commented
@theHamsta I think the bot merged this by accident?

(It doesn't break anything, just removes some `@parameter` highlights)

2021-07-18 17:24 UTC, stsewd commented
> @theHamsta I think the bot merged this by accident?
> 
> (It doesn't break anything, just removes some `@parameter` highlights)

it was by accident, but let's just keep adding improvements in another PR, as you said this doesn't break anything