highlights(markdown): conceal links
nvim-treesitter/nvim-treesitter pull request #3001
Opened 2022-06-09 14:37 UTC by otherJL0

Before:
![markdown_before](https://user-images.githubusercontent.com/54177704/172873714-33b064de-8404-4939-a22b-a9840c8535a1.png)

After:
![markdown_after](https://user-images.githubusercontent.com/54177704/172873746-488743c8-a4e1-4979-8eef-7c3f8b2139a6.png)

I'm still getting antiquated with the query/scheme syntax used by tree-sitter so if there is a better way to write these queries please let me know!

2022-06-11 08:42 UTC, kyazdani42 approved these changes

2022-06-11 10:25 UTC, theHamsta commented
Isn't there a less agressive link concealing that needs to be updated with this PR? (Thinking of the ] to space transformation)

Personally, would not like this concealing because I'm usually more interested in the link address than the link text (especially for intra-repo links) and the change of to the layout is quite huge for long links. Advanced features like this would be a good usecase for settings for concealing (like different levels). Not strictly against merging but we should prepare to have a way to turn this off in future as there might be other complaints in issue of people wanting to turn that off.


Being this the last two weeks without a private computer I'm very inactive at the moment. Should be back next week.

2022-06-11 12:16 UTC, David-Else commented
This is a brilliant change! When I am doing technical writing/documentation the screen gets so full of long links it becomes impossible to read, I then have to use another extension to display the document in the browser... and that brings its own set of problems.

I agree it would be even better if we could switch it on and off, I saw https://github.com/nvim-treesitter/nvim-treesitter/issues/2663 , conceal levels are the perfect solution. I think just having 2 levels, on and off, would be fine.

2022-06-11 12:30 UTC, gegoune commented
I disagree - if it can't be disabled/turned off I would really not like to see that as a default.

2022-06-12 10:15 UTC, kyazdani42 commented
set conceal=0 does disable that though

2022-06-17 13:53 UTC, vigoux approved these changes
My two cents on this: if concealing things is really that much of an issue for you, then use `conceallevel=0`.

2022-06-18 21:58 UTC, theHamsta requested changes
still 
```
(inline_link 
  ["]"] @conceal
  (#set! conceal " "))
```
needs to be update for the new change. The space was there to have a space between the link text and the url This does not make sense when the link url is concealed not

2022-06-21 21:07 UTC, theHamsta approved these changes

2022-06-22 00:14 UTC, otherJL0 commented on queries/markdown/highlights.scm
> +    ")"
Done!

2022-06-22 07:29 UTC, kyazdani42 approved these changes

2022-06-22 11:56 UTC, merged