feat(highlight): re-apply default highlights on colorscheme changes
nvim-treesitter/nvim-treesitter pull request #3235
Opened 2022-07-29 14:57 UTC by jdrouhard

If the plugin is loaded after a colorscheme is set that defines any of
these highlight groups, the default won't be applied. Subsequent
"highlight clear" commands (common when switching colorschemes) will
then clear any of those highlights, but these defaults never have
another opportunity to be initialized.

Effectively, if you load neovim with a colorscheme that has definitions
for some of these highlight groups, then load treesitter, then switch
colorschemes, many of these default links will be absent resulting in
colors that do not appear the same as if that colorscheme had been
used at startup.

Hooking the ColorScheme event with an autocmd that just reapplies these
defaults gives every colorscheme switch the opportunity to get the
defaults for non-explicitly-defined groups.

2022-07-29 15:36 UTC, kyazdani42 approved these changes

2022-07-29 16:31 UTC, vigoux requested changes

2022-07-29 16:31 UTC, vigoux commented on lua/nvim-treesitter/highlight.lua
> +function M.set_default_highlights()
Rather

```suggestion
function M.set_default_hlgroups()
```

2022-07-29 16:32 UTC, jdrouhard commented on lua/nvim-treesitter/highlight.lua
> +function M.set_default_highlights()
Done.

2022-07-30 16:07 UTC, vigoux approved these changes

2022-07-30 18:13 UTC, theHamsta commented
Nice! Thank you!

2022-07-30 18:13 UTC, merged