fix(html): fix wrong indents for script/style tags
nvim-treesitter/nvim-treesitter pull request #4076
Opened 2023-01-02 07:31 UTC by lucario387

HTML was only indenting child elements of element captures, but dedents all end tags (including script/style elements)
Change it so it now only dedents end tag of non-script/style elements
Before:
```html
<body>
  <script>
</script>
</body>
```
After: 
```html
<body>
  <script>
  </script>
</body>
```

2023-01-02 07:55 UTC, theHamsta requested changes
Can you please add your example as a test case?

2023-01-02 08:09 UTC, lucario387 commented
@theHamsta moving this to draft to also tackle #3986 

I will push tests to cover for both cases

2023-01-03 16:31 UTC, lucario387 commented
@theHamsta 

> Can you please add your example as a test case?

Just added tests, can you have a check again?

2023-01-03 16:50 UTC, theHamsta approved these changes

2023-01-03 16:50 UTC, merged