feat: add thrift
nvim-treesitter/nvim-treesitter pull request #4185
Opened 2023-01-20 13:19 UTC by amaanq

This PR adds a thrift parser+queries

cc: @leaxoy since they first brought up thrift in #2282

I'm a little iffy on the queries, so I'd like a few pairs of eyes to review that, but the actual grammar [here](https://github.com/duskmoon314/tree-sitter-thrift/blob/main/grammar.js) is very solid imo and is extensively tested.

Thanks!
-Amaan

2023-01-20 13:21 UTC, amaanq commented
Force pushed due to typo

2023-01-20 13:40 UTC, leaxoy commented
Good job!!

2023-01-20 13:45 UTC, amaanq commented
Force pushed again to bump revision

2023-01-20 13:45 UTC, amaanq commented
> Good job!!

Thanks! :)

2023-01-20 20:12 UTC, ObserverOfTime requested changes

2023-01-20 20:12 UTC, ObserverOfTime commented on queries/thrift/highlights.scm
> +] @character.special
```suggestion
[
  "*"
] @punctuation.special
```

2023-01-20 22:27 UTC, amaanq commented on queries/thrift/highlights.scm
> +(include_path) @definition.import
is there no way to make an include path a special highlight? would be nice

2023-01-20 22:31 UTC, amaanq commented on queries/thrift/highlights.scm
> +] @type.definition
should I remove it or have a definition like

```js
typedef: () => token("typedef")
```
```scm
(typedef) @type.definition
```

..?

2023-01-21 01:45 UTC, amaanq commented
@theHamsta mind if I request for you to review the changes suggested and answer my questions about them? :smile:

2023-01-21 06:58 UTC, ObserverOfTime commented on queries/thrift/highlights.scm
> +(include_path) @definition.import
You can use something like `@string.include` and highlight it however you want locally.

2023-01-21 07:00 UTC, ObserverOfTime commented on queries/thrift/highlights.scm
> +] @type.definition
In e.g. `typedef foo bar`, the `@type.definition` is `bar`.

2023-01-21 11:22 UTC, amaanq commented on queries/thrift/highlights.scm
> +] @type.definition
Ok, fixed that by aliasing identifier to typedef_definition in typedef, thanks!

2023-01-21 11:47 UTC, ObserverOfTime approved these changes

2023-01-21 12:39 UTC, merged