feat: add starlark
nvim-treesitter/nvim-treesitter pull request #4343
Opened 2023-02-18 20:25 UTC by amaanq

cc: @folliehiyuki since he first requested it in #2282

This PR adds support for Starlark: https://github.com/bazelbuild/starlark

It is mainly derived from Python with some minor differences. The two differences I'd like looked over by a maintainer are:

- Imports being replaced by a load() call, where individual strings are a module and as such I'd like to have `@conceal` work for the strings in there, but I could not get that to work and my testing would have the actual "load" keyword concealed.
- Classes being replaced by a struct call, e.g. `a = struct(x=123, y=False, z="string")`, so x/y/z are fields. Only issue is when matching I identified the struct in struct() as `@_func` to capture it later, but it seems like this capture is still visible outside of simply matching. No idea how to remove that.

Thanks,
Amaan

2023-02-18 21:16 UTC, ObserverOfTime requested changes
Use `; inherits: python` instead of duplicating all the python queries.

2023-02-18 21:49 UTC, amaanq commented
> Use `; inherits: python` instead of duplicating all the python queries.

There's a bunch to delete since they're not a part of Starlark's grammar, like try/catch/raise/finally; is it possible to inherit python and remove those too? If so, how?

2023-02-19 07:36 UTC, ObserverOfTime commented
You could move the relevant queries to a separate directory (like `html` / `html_tags`) and inherit from that in both but I don't think it's worth it in this case.

Can you at least explicitly separate the starlark queries from the python ones with a comment (e.g. `;; starlark queries`)?

2023-02-20 13:46 UTC, amaanq commented
> You could move the relevant queries to a separate directory (like `html` / `html_tags`) and inherit from that in both but I don't think it's worth it in this case.
> 
> Can you at least explicitly separate the starlark queries from the python ones with a comment (e.g. `;; starlark queries`)?

Yeah, now highlights and locals have a section for this , injections inherits from Python, and folds/indents only contain removed items

2023-02-20 13:58 UTC, ObserverOfTime approved these changes

2023-02-22 12:06 UTC, FollieHiyuki commented
Sorry for the late reply. I just tried this branch today on some of my simple Bazel build files. Looks good to me.

Thanks for the work!

2023-02-22 20:00 UTC, amaanq commented
> 1 last comment though. Does it need to be applied only to `bzl` files? Other programs use Starlark too (e.g. [ascode](https://github.com/mcuadros/ascode), [isopod](https://github.com/cruise-automation/isopod))

I didn't know about starlark having its own extension too...that has some bugs that I'm fixing rn.
I see two solutions, recognize both .bzl and .star for the filetypes that tree-sitter-starlark can parse, or set bzl files to starlark filetypes in vim (the latter is easier but feels more incorrect, I'm not sure if we can set two filetypes for one grammar)

2023-02-22 20:53 UTC, amaanq commented
Related: https://github.com/vim/vim/pull/12049

2023-02-23 22:09 UTC, amaanq commented
This is ready to merge FYI, ft detection was merged as well :)

2023-02-23 23:28 UTC, theHamsta approved these changes

2023-02-23 23:28 UTC, merged

2023-02-23 23:28 UTC, theHamsta commented
Thank you!

2023-02-25 03:38 UTC, FollieHiyuki commented
I saw the PR got merged, but I'm still putting my final comment here.

Yes, recognizing `*.bzl` as Starlark filetype is the correct way in my opinion. Having the filetype detection for `*.bzl` and `*.star` would be enough for most cases. The users can always add their application-specific extensions to `filetype.lua`.

2023-02-25 03:54 UTC, amaanq commented
While I did get Starlark ft detection merged upstream, I think it's ok to leave it as is (and keep .bzl as Bazel files...oh well)