feat: add lua patterns
nvim-treesitter/nvim-treesitter pull request #4433
Opened 2023-03-03 10:49 UTC by amaanq

Alternative to #3578

2023-03-03 10:51 UTC, clason commented
maybe mark it as experimental for now, then? 

(*ceterum censeo* we _really_ need to start categorizing parsers and taking that seriously)

2023-03-03 10:53 UTC, amaanq commented
> maybe mark it as experimental for now, then?
> 
> (_ceterum censeo_ we _really_ need to start categorizing parsers and taking that seriously)

Categorize them in what way? I do try to help out with parsers that aren't the best as much as possible..but I'm only 1 person :laughing:

2023-03-03 10:56 UTC, clason commented
> Categorize them in what way? 

In tiers, like "core", "community maintained", "experimental", "broken" -- and then handle these differently in our CI/documentation (e.g., don't auto-update experimental or broken languages, and don't include them in the build tests etc.)

Basically, keep the list of maintainers updated, and drop maintainers (and parser tiers) aggressively.

This would also help with expectation management, so people could only install "core" languages and be confident that they work well and don't break too often.

> I do try to help out with parsers that aren't the best as much as possible..but I'm only 1 person 😆

Yes, precisely, and we need to make sure your efforts are not wasted ;)

2023-03-03 11:00 UTC, amaanq commented
> In tiers, like "core", "community maintained", "experimental", "broken" -- and then handle these differently in our CI/documentation (e.g., don't auto-update experimental or broken languages, and don't include them in the build tests etc.)

Yeah that is a **really** good idea, and could help with the CI breaking ever so often..would "core" be those at tree-sitter? And say a self-made parser (by me or anyone else but NOT at tree-sitter) be "community maintained"?

2023-03-03 11:01 UTC, amaanq commented
Here's some screenshots anyways, one thing I kept in mind was keeping consistency with Regex highlights:

![image](https://user-images.githubusercontent.com/29718261/222703854-970afb0f-8eec-4422-afdd-fca61b6e6ee4.png)

![image](https://user-images.githubusercontent.com/29718261/222703923-bb7eaf56-bf49-4383-8256-b6c07053a616.png)

![image](https://user-images.githubusercontent.com/29718261/222703970-8ca2dea4-ccdc-4049-a251-46c684c51710.png)

2023-03-03 11:16 UTC, clason commented
> Yeah that is a **really** good idea, and could help with the CI breaking ever so often..would "core" be those at tree-sitter? And say a self-made parser (by me or anyone else but NOT at tree-sitter) be "community maintained"?

No, those would be parsers that nvim-treesitter core maintainers (like you ;)) care about enough to keep running (or that are stable enough that no maintenance is necessary).

"community" would be those maintainers we always need to ping manually (which could be automated as well).

(TL;DR: it's about maintaining the _queries_ here, not the parsers upstream.)

2023-03-03 11:20 UTC, amaanq commented
Man that windows ci is taking forever...typical

Feel free to merge whenever so that your neovim PR can be updated accordingly :)  (as long as class being captured as `@keyword` is ok to you)

2023-03-03 12:04 UTC, amaanq commented
Text inside brackets weren't highlighted as `@constant` (e.g. A and Z in A-Z), classes inside brackets weren't highlight as `@keyword` because for whatever reason the inner class node is hidden (_class) and is used there, and I added fixes to only inject inside the string content and inject in both parameters for gsub/gmatch (both can have luap but before it was only injecting into the first), and maybe some other things I forgot

2023-03-04 09:58 UTC, ObserverOfTime approved these changes

2023-03-04 11:18 UTC, amaanq commented
Switched to my fork, queries look nicer and capture better as well

2023-03-04 11:20 UTC, amaanq commented
cc @max397574 iirc you expressed interest in this

2023-03-04 11:55 UTC, ObserverOfTime requested changes

2023-03-04 11:55 UTC, ObserverOfTime commented on queries/luap/highlights.scm
> +  "^" @string.regex
I'd make this one `@operator` too.
```suggestion
  "^" @operator
```

2023-03-04 16:32 UTC, ObserverOfTime approved these changes

2023-03-04 16:32 UTC, merged