Add support for ponylang
nvim-treesitter/nvim-treesitter pull request #4500
Opened 2023-03-13 08:43 UTC by mfelsche

This add support for ponylang by adding the parser to the supported parsers, setting the revision etc.

The queries seem legit. Highlighting works well. All queries have been tested in the tree-sitter playground and with nvim-treesitter as good as possible.

2023-03-16 09:21 UTC, ObserverOfTime requested changes

2023-03-16 09:21 UTC, ObserverOfTime commented on queries/ponylang/highlights.scm
> +;; references to upper case things are considered constructors
```suggestion
;; upper case identifiers are considered types
```

2023-03-16 09:21 UTC, ObserverOfTime commented on queries/ponylang/highlights.scm
> +] @keyword.return
I think only "return" should be here.

2023-03-16 09:21 UTC, ObserverOfTime commented on queries/ponylang/highlights.scm
> +] @keyword.control
Move these to the `@keyword` group.

2023-03-16 09:21 UTC, ObserverOfTime commented on queries/ponylang/highlights.scm
> +] @storageclass
"var" and "let" should be `@keyword`.

2023-03-16 09:21 UTC, ObserverOfTime commented on queries/ponylang/highlights.scm
> +] @keyword.function
"be" should be `@keyword.coroutine`.
"new" should be `@keyword.operator`.

2023-03-16 09:21 UTC, ObserverOfTime commented on queries/ponylang/textobjects.scm
Text-objects go in [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects).

2023-03-16 09:21 UTC, ObserverOfTime commented on lockfile.json
> +    "revision": "v0.0.2"
This should be the commit hash.

2023-03-16 09:21 UTC, ObserverOfTime commented on lua/nvim-treesitter/parsers.lua
> +    revision = "v0.0.2",
It should (normally) not be hardcoded here.

2023-03-17 07:47 UTC, mfelsche commented
Thanks for the review @ObserverOfTime I am reworking the whole tree-sitter grammar with @amaanq so, this whole PR is going to change drastically. I will incoporate your remarks in that. Stay tuned.

2023-03-27 15:01 UTC, closed without merging