Add Python else elif dedent
nvim-treesitter/nvim-treesitter pull request #4618
Opened 2023-04-08 03:57 UTC by lucario387

not guarantee to work, just testing the waters 

- If this doesn't work so well, maybe changing the indent algo instead
- Does not support multiline elif statement

2023-04-26 06:06 UTC, lucario387 commented
This is mostly just a QOL for when in error nodes

 For example:
```python
if True:
  ...
  else:
```
It will change to 
```python
if True:
  ...
else:
```

2023-04-26 06:17 UTC, ObserverOfTime approved these changes

2023-04-26 18:19 UTC, theHamsta requested changes
Can we have some tests for the changes?

2023-04-26 22:50 UTC, lucario387 commented
> Can we have some tests for the changes?

Just added one.

2023-04-29 08:35 UTC, theHamsta approved these changes

2023-04-29 08:35 UTC, merged