feat: Add haxe parser and queries.
nvim-treesitter/nvim-treesitter pull request #5213
Opened 2023-08-10 01:16 UTC by vantreeseba

2023-08-10 08:48 UTC, ObserverOfTime requested changes

2023-08-10 08:48 UTC, ObserverOfTime commented on lua/nvim-treesitter/parsers.lua
> +  filetype = "haxe",
This is unnecessary.

```suggestion
```

2023-08-10 08:48 UTC, ObserverOfTime commented on queries/haxe/highlights.scm
> +(preprocessor_statement) @tag
```suggestion
(preprocessor_statement) @preproc
```

2023-08-10 08:48 UTC, ObserverOfTime commented on queries/haxe/injections.scm
> +(comment) @jsdoc
```suggestion

((comment) @jsdoc
 (#lua-match? @jsdoc "^/[*][*][^*].*[*]/$"))
  
```

2023-08-10 08:48 UTC, ObserverOfTime commented on queries/haxe/highlights.scm
> +(pair [":" "=>"] @punctuation.special)
Assuming "@" is a token.

```suggestion
[ "@" ":" ] @punctuation.special
(pair "=>" @punctuation.special)
```

2023-08-10 08:48 UTC, ObserverOfTime commented on queries/haxe/highlights.scm
> +) @embedded
We don't have `@embedded`. This should work.

```suggestion
) @none
```

2023-08-10 12:48 UTC, lucario387 commented on queries/haxe/highlights.scm
> +  (_(_(_(_(_ (identifier) @method .)))))
I know that this is a way to workaround with issue from upstream, but I'd prefer these to be commented out in nvim-treesitter queries. You can add it back from local config anyways.

2023-08-10 12:49 UTC, lucario387 commented on queries/haxe/tags.scm
Please remove.

2023-08-10 12:52 UTC, lucario387 commented on tests/query/highlights/haxe/class.hx
> +//    ^ variable
Shouldn't this be `@type`? also for interfaces

2023-08-10 12:55 UTC, lucario387 commented
Please don't bring the entire test suite from `tree-sitter-haxe` to here. Instead, bring only tests that reflect specific changes to accomodate with `nvim-treesitter` differences.

2023-08-10 12:55 UTC, clason reviewed
Since you seem to be copying the upstream queries verbatim: Are you aware that Neovim uses a different query order precedence ("last match wins") than upstream ("first match wins")?

2023-08-10 12:55 UTC, clason commented on queries/haxe/locals.scm
> +] @scope @local.scope
We don't use the upstream format (yet).

2023-08-10 15:05 UTC, vantreeseba commented
Thanks for all the feedback / reviews, will try to get to those soon.

2023-08-12 15:49 UTC, clason commented
We've just switched the format of injection queries to that of upstream (see CONTRIBUTING.md). You'll have to rebase on (not merge in!) `master` and adapt `injections.scm`, sorry.

2024-02-16 09:53 UTC, clason commented
Closing as stale; if people still want this, it's better to start from scratch based on the current state of the parser and our contributing guidelines.

2024-02-16 09:54 UTC, closed without merging