fix(php): fix indentation for in between braces
nvim-treesitter/nvim-treesitter pull request #5489
Opened 2023-10-06 17:52 UTC by afonsocarlos

This is an improvement fix on top of the #3591 so indentation also works properly in cases like:

```php
<?php

function test() {
    $array = [|] // insert new line in between braces
}
```

2023-10-06 17:57 UTC, afonsocarlos commented
Additionally, the test for `unfinished-call.php` was incorrectly updated some commits ago. The expected behavior must be to keep the indentation level until closing "function call", not resetting the cursor position to 0. This PR also fixes that as a side effect.

2023-10-06 18:09 UTC, lucario387 requested changes

2023-10-06 18:09 UTC, lucario387 commented on queries/php/indents.scm
> +(ERROR "(" @indent.align (#set! indent.open_delimiter "(") (#set! indent.close_delimiter ")") . (_))
Reading this is very hard to understand

```suggestion
(ERROR
  "(" @indent.align
  . (_)
  (#set! indent.open_delimiter "(")
  (#set! indent.close_delimiter ")"))
```

2023-10-07 23:52 UTC, lucario387 approved these changes

2023-10-15 18:34 UTC, merged