Add the templ parser
nvim-treesitter/nvim-treesitter pull request #5667
Opened 2023-11-12 21:23 UTC by vrischmann

This adds the [tree-sitter-templ](https://github.com/vrischmann/tree-sitter-templ) parser.

2023-11-13 06:41 UTC, amaanq commented
Are you unable to inherit go's queries?

2023-11-13 08:18 UTC, vrischmann commented
> Are you unable to inherit go's queries?

Do you mean with this
```
; inherits: lang1,(optionallang)
```
as described in [CONTRIBUTING.md](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md) ?
I haven't tried it yet, I'll have to check.

2023-11-13 22:02 UTC, vrischmann commented
(I'm documenting this here so others may find it; it's hard to find any relevant info searching for this error).

Ok so I tried to use `; inherits: go` and at first I was only getting an error like this:
```
ERR 2023-11-13T22:44:59.606 nvim.41136.0 decor_provider_invoke:47: error in provider treesitter/highlighter:line: Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:260: query: invalid node type at position 1266 for language templ
stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:260: in function 'get'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:50: in function 'new'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:202: in function 'get_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:228: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:345: in function 'for_each_tree'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:214: in function 'on_line_impl'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:290: in function </usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:284>
```

I struggled to understand the problem but after some digging I realized that the queries in `nvim-treesitter` were not compatible with the version of `tree-sitter-go` I was using in my parser (0.19.1).

I updated `tree-sitter-go` to 0.20.0, fixed a bunch of things and now it works.

The queries files now only contain things that are specific to templ.

2023-11-13 22:49 UTC, ObserverOfTime requested changes

2023-11-13 22:49 UTC, ObserverOfTime commented on queries/templ/injections.scm
> +
```suggestion

((element_comment) @injection.content (#set! injection.language "comment"))

```

2023-11-13 22:49 UTC, ObserverOfTime commented on queries/templ/highlights.scm
> +] @operator
```suggestion
"@" @operator
```

2023-11-13 22:49 UTC, ObserverOfTime commented on queries/templ/highlights.scm
> +(style_element) @tag
```suggestion
[
  (tag_start)
  (tag_end)
  (self_closing_tag)
  (style_element)
] @tag
```

2023-11-13 22:49 UTC, ObserverOfTime commented on queries/templ/highlights.scm
> +(style_element_text) @string.special
```suggestion
[
  (element_text)
  (style_element_text)
] @string.special
```

2023-11-13 22:49 UTC, ObserverOfTime commented on queries/templ/highlights.scm
> +(dynamic_class_attribute_value) @function.method
```suggestion
[
  (expression)
  (dynamic_class_attribute_value)
] @method
```

2023-11-15 21:58 UTC, ObserverOfTime approved these changes

2023-11-15 23:00 UTC, vrischmann commented
There was an error in one of the query which made the checks fail, it's fixed now.

2023-11-16 21:12 UTC, amaanq approved these changes

2023-11-16 21:12 UTC, merged