Fix Julia pipe function highlight
nvim-treesitter/nvim-treesitter pull request #5815
Opened 2023-12-21 01:56 UTC by degnbol

In Julia when piping into a function the function should be highlighted as a function call, and not a variable.
This change adds `@function.call` to any identifier that are piped into by matching the operator in a binary_expression against the string "|>". It also annotates the operator with `@pipe`, as a side-effect.

2023-12-21 08:02 UTC, ObserverOfTime requested changes

2023-12-21 08:02 UTC, ObserverOfTime commented on queries/julia/highlights.scm
> +  (#lua-match? @pipe "|>"))
```suggestion
  (operator) @_pipe
  (identifier) @function.call
  (#eq? @_pipe "|>"))
```

2023-12-21 08:47 UTC, clason commented
@savq

2023-12-22 03:58 UTC, savq commented
The change is ok. I agree with ObserverOfTime suggested changes.


\<rant>
In PLs with first-class functions, highlighting a function identifier is a best effort thing. I think `@function.call` should signify the _application_, not for the function itself.


This is the type of thing we wouldn't need to worry about if LS.jl had semantic highlights tho.
\</rant>

2023-12-22 09:35 UTC, clason commented
<rant>
Don't get me started on LS.jl...

"Oh, let's write a language server for Julia in Julia! It'll be grand!" ... *Runs away giggling*.
</rant>

2023-12-22 09:37 UTC, ObserverOfTime commented
> "Oh, let's write a language server for Julia in Julia! It'll be grand!" ... _Runs away giggling_.

Well R's language server is written in R and it's pretty good. :^)

2023-12-22 10:07 UTC, clason commented
@savq instead of `@pipe`, would `@operator` be suitable here (in case you _want_ to capture it)?

2023-12-22 10:09 UTC, ObserverOfTime commented
I assumed it's already captured elsewhere.

2023-12-22 10:10 UTC, clason commented
Ah, yes, it is.

2023-12-22 10:12 UTC, clason approved these changes

2023-12-22 10:24 UTC, ObserverOfTime approved these changes

2023-12-22 10:24 UTC, merged