feat: folds for git config files
nvim-treesitter/nvim-treesitter pull request #5850
Opened 2024-01-04 05:07 UTC by ribru17

Defines folds for sections of `.gitconfig` files, like the following:
```.gitconfig
# this is its own fold section
[core]
	editor = nvim
	pager = delta

# and here
[credential]
	helper = libsecret

# and here
[delta]
	navigate = true
	syntax-theme = Dracula
	side-by-side = false
	line-numbers = true
```

2024-01-17 14:59 UTC, clason commented
Please don't merge master into a PR branch; instead `git rebase` it.

2024-01-17 15:02 UTC, ribru17 commented
Apologies, I Github-synced this branch by accident

2024-01-17 15:02 UTC, ribru17 commented
> (Also, you might want to get ahead of the curve and apply the formatting from the backport PR.)

Exactly why I was messing with this! :joy:

2024-01-17 15:02 UTC, clason commented
Yeah, that button is a trap.

2024-01-20 10:10 UTC, clason approved these changes

2024-01-20 10:39 UTC, clason requested changes
Please rebase(!) on master.

2024-01-20 10:45 UTC, clason approved these changes

2024-01-20 10:45 UTC, lucario387 commented
oops :sob: 

Very sorry for that. It's fixed now

2024-01-20 10:46 UTC, clason commented
@lucario387 didn't mean you, for the record; I just wanted you to review the changes.

2024-01-20 10:46 UTC, merged

2024-01-20 10:49 UTC, lucario387 commented
I unintentionally amend @ribru17 commit into latest master so that's my fault :sob: