feat: Update wit version
nvim-treesitter/nvim-treesitter pull request #6508
Opened 2024-04-25 16:17 UTC by liamwh

2024-04-25 16:32 UTC, clason commented on README.md
> +- [x] [wit](https://github.com/liamwh/tree-sitter-wit) (experimental, maintained by @liamwh)
Rebase error?

2024-04-26 08:14 UTC, liamwh commented on README.md
> +- [x] [wit](https://github.com/liamwh/tree-sitter-wit) (experimental, maintained by @liamwh)
Resolved, thx for pointing this out

2024-04-26 08:29 UTC, clason commented
Please drop your changes to the readme entirely.

2024-04-26 08:31 UTC, ObserverOfTime requested changes

2024-04-26 08:31 UTC, ObserverOfTime commented on README.md
Don't edit the readme. The space doesn't matter and the extra line will be removed by CI.

2024-04-26 08:31 UTC, ObserverOfTime commented on queries/wit/highlights.scm
> +(valid_semver) @property
```suggestion
(valid_semver) @string.special
```

2024-04-26 08:31 UTC, ObserverOfTime commented on queries/wit/highlights.scm
> +  (id) @property)
```suggestion
  (id) @attribute)
```

2024-04-26 10:46 UTC, liamwh commented on queries/wit/highlights.scm
> +  (id) @property)
Done ✅

2024-04-26 10:46 UTC, liamwh commented on README.md
Done, removed README

2024-04-26 10:52 UTC, liamwh commented on queries/wit/highlights.scm
> +  "interface"
Agreed, done.

2024-04-26 11:18 UTC, ObserverOfTime approved these changes

2024-04-26 15:06 UTC, ObserverOfTime commented on queries/wit/highlights.scm
> +(comment) @comment
```suggestion
(comment) @comment @spell
```
Forgot this one.

2024-04-26 15:41 UTC, liamwh commented on queries/wit/highlights.scm
> +] @type.definition
Done ✅

2024-04-26 16:03 UTC, liamwh commented on queries/wit/highlights.scm
> +] @type.definition
Done ✅

2024-04-28 09:16 UTC, clason commented on queries/wit/injections.scm
> +((comment) @comment
@liamwh can you make that change? This is the last blocker, and I want to stop having to drop `wit` from the automated parser updates.

2024-04-28 13:25 UTC, clason requested changes

2024-04-28 13:25 UTC, clason commented on queries/wit/injections.scm
> +((comment) @comment
(And I can't make that change since you did not make this PR from a feature branch 😞 )

2024-04-28 15:51 UTC, clason commented on queries/wit/highlights.scm
> +(comment) @injection.content @spell
no, not here -- in the injections.scm!

2024-04-28 15:53 UTC, liamwh commented on queries/wit/injections.scm
> +((comment) @comment
I have created the change, but kept `@spell`, so the line now reads `(comment) @injection.content @spell`. Is this now correct?

2024-04-28 15:54 UTC, liamwh commented on queries/wit/highlights.scm
I removed this as result is actually a builtin type.

2024-04-28 15:55 UTC, clason commented on queries/wit/injections.scm
> +((comment) @comment
Nope, sorry. This comment is on the injections, not the highlights.

2024-04-28 15:57 UTC, liamwh commented on queries/wit/injections.scm
> +((comment) @comment
Ok thanks for that, it should be correct now

2024-04-28 15:58 UTC, clason commented on queries/wit/injections.scm
> +((comment) @comment
Still no 😞

2024-04-28 15:59 UTC, clason requested changes
Like so (and only so; pay attention to the different files).

2024-04-28 15:59 UTC, clason commented on queries/wit/highlights.scm
> +(comment) @injection.content @spell
```suggestion
(comment) @comment @spell
```

2024-04-28 15:59 UTC, clason commented on queries/wit/injections.scm
> +((comment) @comment
```suggestion
((comment) @injection.content
```

2024-04-28 16:06 UTC, clason commented
You know what? I'll take care of it.

2024-04-28 16:06 UTC, clason commented
Superseded by #6527

2024-04-28 16:06 UTC, closed without merging