javascript: : in pairs as punctuation.delimiter
nvim-treesitter/nvim-treesitter pull request #684
Opened 2020-11-22 17:21 UTC by rockerBOO

![2020-11-22-122036_4480x1440_scrot](https://user-images.githubusercontent.com/15027/99910644-2ec47480-2cbd-11eb-9025-fa5179b744fd.png)

2020-11-22 17:49 UTC, kyazdani42 commented
in rust we do not highlight this, in lua we highlight `=` as operator in a table. Is this really a punctuation delimiter or a assignment character ^^ ?

2020-11-22 18:02 UTC, rockerBOO commented
mmm I like operator better here. I was replicating the matching from typescript for object type definition `type X {x: Type}` and type delimiter `x: MyType`. I still like operator but should all these  match or are they different?

2020-11-22 19:14 UTC, rockerBOO commented
Changed `:` to be an operator.

2020-11-22 20:50 UTC, steelsojka commented
I don't think I would consider this an operator at all. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#Table 

If you want a it colored a specific way I would extend the javascript query and give a custom highlight group. I think this might add confusion for some colorschemes.

2020-11-22 22:00 UTC, rockerBOO commented
https://tc39.es/ecma262/#sec-punctuators
This has `:` in the list of punctuators. I think returning this back to `(pair ":" @punctuation.delimiter` would be appropriate.

2020-11-22 22:11 UTC, kyazdani42 commented
well depends, but for me `:` in an object is an operator for variable assignment kind of. Just to keep consistency between language, but i wouldn't mind highlighting as a punctuation delimiter (although `:` is not a delimiter, `;` is, or maybe my english is just too limited in this area to understand properly :) )

2020-11-22 22:45 UTC, rockerBOO commented
https://tc39.es/ecma262/#sec-object-initializer

This is the object initializer spec. This spec has these punctuations `{` `}` `,` `:`. 
`{`, `}` are `punctuation.bracket`. 
`,` is `punctuation.delimiter`

> [delimiter](https://www.merriam-webster.com/dictionary/delimiter): a character that marks the beginning or end of a unit of data

Using this definition, the delimiter of a key: value is `:`. 

I feel now that `punctuation.delimiter` matches throughout and matches the spec.

2020-11-22 23:34 UTC, rockerBOO commented
To further confuse things Atom sets it as a operator. (If I am reading properly)

https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L386

2020-11-23 12:53 UTC, steelsojka requested changes

2020-11-23 12:53 UTC, steelsojka commented on queries/javascript/highlights.scm
> +(pair ":" @punctuation.delimiter)
Can you move this to the section with the other punctuation?

2020-11-23 16:13 UTC, rockerBOO commented
Updated the positioning of this query.

2020-11-23 17:06 UTC, steelsojka commented
> To further confuse things Atom sets it as a operator. (If I am reading properly)
> 
> https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L386

I tried to look in the text mate grammar for vscode's highlighting to try and compare and I couldn't navigate it very well. If you find another case this is tagged as an operator, we can just change it in another PR. I'm good this for now if you are.

2020-11-23 17:07 UTC, steelsojka approved these changes

2020-11-23 17:07 UTC, merged