feat(ruby): detect shebang directive
nvim-treesitter/nvim-treesitter pull request #7140
Opened 2024-09-11 11:28 UTC by jeromedalbert

Detect shebangs as directives that are distinct from comments.

Before:
![Screenshot 2024-09-11 at 4 26 50 AM](https://github.com/user-attachments/assets/75cebac0-70d8-4383-a000-5c4e1e665d2e)

After:
![Screenshot 2024-09-11 at 4 27 22 AM](https://github.com/user-attachments/assets/ef5b261d-6fd3-49b7-ba84-12a89a32f0da)

2024-09-11 11:37 UTC, clason requested changes

2024-09-11 12:14 UTC, clason commented
@TravonteD

2024-09-12 03:56 UTC, ribru17 commented
Why not only apply highlights if the comment *is* a shebang? Seems like the shebang is still a comment (as well as a message to the kernel)

2024-09-12 04:38 UTC, jeromedalbert commented
I was trying to highlight comments and shebangs differently. Since then I figured it was mostly pointless and would go against how other languages like Bash highlight shebangs.

I updated the PR by copy/pasting the Bash [shebang highlights](https://github.com/nvim-treesitter/nvim-treesitter/blob/b6a6d8997c46dc15682020ce4fddc5a89ee1ac0d/queries/bash/highlights.scm#L236-L239) and it works well.

2024-09-15 09:31 UTC, clason approved these changes

2024-09-17 02:13 UTC, merged