feat(slim): add parser, queries and tests
nvim-treesitter/nvim-treesitter pull request #7425
Opened 2024-12-02 10:49 UTC by theoo

2024-12-02 11:15 UTC, clason requested changes
Please read CONTRIBUTING.md; you are only(!) allowed to use captures listed there. Please use the most specific matching capture (prefer `@keyword.import` over just `@keyword` etc.)

2024-12-02 11:15 UTC, clason commented on queries/slim/injections.scm
> + (#set! injection.combined))
```suggestion
```

We don't have a parser for coffeescript.

2024-12-02 11:16 UTC, clason commented
You can (and need to) run `./scripts/format-queries.lua queries/slim`.

2024-12-06 05:41 UTC, ribru17 commented on queries/slim/highlights.scm
> +  (#any-of? @markup.heading "header" "h1" "h2" "h3" "h4" "h5" "h6")
We actually have more specific headings for each of these (e.g. `@markup.heading.3`)

2024-12-06 05:41 UTC, ribru17 commented on queries/slim/injections.scm
> +((textile_lang) @injection.content
We also don't have `textile` (yet? :))

2024-12-06 05:41 UTC, ribru17 commented on queries/slim/highlights.scm
> + (text_block)
Maybe this one should be `@markup.raw.block`?

2024-12-06 05:41 UTC, ribru17 commented on queries/slim/highlights.scm
> +(comment) @comment
```suggestion
(comment) @comment @spell
```

2024-12-06 05:41 UTC, ribru17 commented on queries/slim/injections.scm
Please also add comment injections

2024-12-15 21:41 UTC, theoo commented
Thanks for your feedback and patience. I tried to run `scripts/run_tests.sh` without success. The _minimal_init.lua_ config file has reference to a missing file. _plugin/plenary.vim_ , therefore the script exists with something like `PlenaryBustedDirectory is not an editor command`.

An existing issue might be related: https://github.com/nvim-treesitter/nvim-treesitter/issues/3837

I wasn't able to fix it. Should I open a ticket for that?

2024-12-15 22:05 UTC, clason commented
No, you need to install plenary to run the tests.

https://github.com/nvim-lua/plenary.nvim

2024-12-15 22:29 UTC, theoo commented
It's installed through _my setup_ but the script is loading an alternative config/init file:
```bash
run() {
    nvim --headless --noplugin -u scripts/minimal_init.lua \
        -c "PlenaryBustedDirectory $1 { minimal_init = './scripts/minimal_init.lua' }"
}
```
And the minimal_init.lua file references a missing file, it seems:
```lua
vim.opt.runtimepath:append "."
vim.cmd.runtime { "plugin/plenary.vim", bang = true } -- there is no such file
vim.cmd.runtime { "plugin/nvim-treesitter.lua", bang = true }
```
So unless I'm missing something important about neovim paths, I won't be able to load plenary that way, when installed with Lazy.

Anyways, I will just remove the highlight test. It works just fine with `tree-sitter test` but the comments structure is odd with slim, so I can see where it breaks in the _highlights_spec.lua_ file.

2024-12-15 22:33 UTC, clason commented
>  when installed with Lazy.

Yep, that's the issue.

2024-12-16 03:19 UTC, ribru17 commented
Pretty sure you need to set `ft=slim` with a modeline in the injection test files, otherwise tests wont pass

2025-01-15 19:21 UTC, clason commented
@theoo friendly ping. (I don't think the tests are actually valuable enough here, anyway.)

2025-01-15 19:21 UTC, clason commented on queries/slim/highlights.scm
> +; and https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights
```suggestion
```
Not needed here.

2025-01-15 20:16 UTC, theoo commented
TLDR; I have a tab (1 of 8 :-) only) in my browser for that and I will fix it ASAP, probably in the coming days.

Sorry for the delay, and thank you for the patience. Something came up.

I'm not able to run the test locally due to how Plenary is loaded in my config (Lazy), and I didn't take the time to write an alternative minimal neovim config just for to run test. It's obiously not making sense to continue pushing arbitrary changes in the hope test wil pass in the pipeline, I must run tests locally before submitting the next changes.

2025-01-15 20:18 UTC, clason commented
You can just remove the tests; they are not a hard requirement.

2025-01-19 12:57 UTC, theoo commented
I have not been able to run tests locally, so I removed injections tests (cannot debug here because I don't even understand the error and suggested to do so).

Setup: Archlinux, Neovim v0.10.3, latest Plenary (3707cdb) loaded without plugins manager.

Issues: 
- `highlight-assertions` fails to compile
- `vim/_editor.lua:0: command line..script nvim_exec2() called at command line:0..BufEnter Autocommands for "<buffer=1>": Vim(append):Error executing lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:107: no parser for 'scheme' language`

I was wondering if something speaks agains packing tests in docker? I didn't find a list of dependencies, but I can help writing the Dockerfile if needed.

2025-01-19 16:26 UTC, ribru17 commented
Local runs are indeed a mess; that said, it looks like tests would have failed because:

1. languages need an `@` (e.g. `^ @javascript`)
2. since vim has no slim filetype, every test injection file would need a modeline like `// vim: ft=slim` or equivalent

2025-01-19 16:29 UTC, clason commented
And thanks for the offer, but for 1.0 (`main` branch WIP) we plan to rework the tests to avoid the private crate (and plenary) anyway.

2025-01-19 16:30 UTC, clason commented on README.md
> +- [x] [slim](https://gitlab.com/theoreichel/tree-sitter-slim) (maintained by @theoreichel)
This file is autogenerated, so it should match the parser information.

2025-01-19 16:31 UTC, clason commented on lua/nvim-treesitter/parsers.lua
> +  maintainers = { "@theoo", "@theoreichel" },
That's the same person, right, just github and gitlab user names? If so, please remove the Gitlab username; the point of this information is to record who should be pinged on issues and PRs related to these queries(!), and that would obviously not work across code forges.

2025-01-20 08:15 UTC, theoo commented on README.md
> +- [x] [slim](https://gitlab.com/theoreichel/tree-sitter-slim) (maintained by @theoreichel)
Changes removed as the file is generated.

2025-01-20 08:16 UTC, theoo commented
@ribru17 Thank you for the explanation. I'll be happy to provide injection tests (or any useful tests for that matter). @clason mentioned that they are not mandatory so should I open a new PR once this one is (eventually) approved, or would you rather have them in this very PR?

I feel uncomfortable to do this if I cannot run tests locally.

2025-01-20 08:17 UTC, clason commented on lua/nvim-treesitter/parsers.lua
> +    url = "https://github.com/theoo/tree-sitter-slim",
(It's fine to point to your gitlab repo here, by the way; it's just about the maintainers entry which needs to be a user on Github -- the "owner" is clear from the repo URL.)

2025-01-20 08:18 UTC, clason commented on lua/nvim-treesitter/parsers.lua
> +  experimental = true,
Sorry, but we don't accept experimental parsers anymore. If the grammar is not suitable for daily use (because the syntax is not fully covered or breaking changes are expected), then it's better to wait.

If it is, then it's not experimental ;)

2025-01-20 15:39 UTC, ribru17 commented on queries/slim/highlights.scm
> +; and https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights
I think after removing these comments and adding 

```scm
[
  "#{"
  "}"
] @punctuation.special
```

this should be good to go

2025-01-21 08:07 UTC, theoo commented on queries/slim/highlights.scm
> +; and https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights
Thanks for the good suggestion. I updated it upstream as well.

2025-01-21 08:25 UTC, merged

2025-01-21 09:42 UTC, theoo commented
Thank you for your support and help!