feat: add java indent
nvim-treesitter/nvim-treesitter pull request #965
Opened 2021-02-20 11:28 UTC by elianiva

2021-02-20 11:37 UTC, kyazdani42 commented
@p00f could you check that this is right ?

2021-02-20 11:38 UTC, p00f commented
sure just a sec

2021-02-20 11:55 UTC, p00f commented
for argument list i couldn't find an authoritative style guide but shouldn't it be in one line?
![image](https://user-images.githubusercontent.com/36493671/108594533-8f3c7e00-73a0-11eb-9777-0bf2d6ad3f4a.png)
The rest is nice!

2021-02-20 11:58 UTC, elianiva commented
I don't know about that either :laughing:
I just add the indent query because I recently started writing java at my school so I still don't know much about it.

2021-02-20 11:58 UTC, p00f commented
this is better than 
![image](https://user-images.githubusercontent.com/36493671/108594606-fce8aa00-73a0-11eb-81c9-a8ebf89a3cd5.png)
though, so I'm fine

2021-02-20 11:58 UTC, p00f approved these changes

2021-02-20 12:02 UTC, p00f requested changes

2021-02-20 12:02 UTC, p00f commented on queries/java/indents.scm
> +  (argument_list)
```suggestion
  (argument_list)
  (formal_parameters)
```
Indentation of formal_parameters behaves the same way (not ideal that is), but better than nothing

2021-02-20 12:03 UTC, p00f commented on queries/java/indents.scm
> +  (argument_list)
@theHamsta is the cpp maintainer, can you shed light?

2021-02-20 12:13 UTC, p00f commented
Same with array_initializer
![image](https://user-images.githubusercontent.com/36493671/108594960-1854b480-73a3-11eb-9e68-89416d181078.png)

2021-02-21 13:40 UTC, p00f approved these changes

2021-02-21 14:04 UTC, elianiva commented
I have a question, not related to indent but still related to Java. Do we want to inject jsdoc for java comments? They both are very similar, but I'm not sure if it's a good idea.

2021-02-21 14:08 UTC, kyazdani42 approved these changes

2021-02-21 14:08 UTC, merged

2021-02-21 14:09 UTC, kyazdani42 commented
@elianiva i don't know java much, but if they do not use jsdoc, i don't think we should enable injection for it :)

2021-02-21 14:15 UTC, elianiva commented
That makes sense, I'll just do it locally then.

2021-02-21 15:20 UTC, theHamsta commented
Maybe this could work. Jsdoc and javadoc pretty much look the same.