Support the glimmer parser when the `hbs` template literal tag is used
nvim-treesitter/nvim-treesitter pull request #985
Opened 2021-02-28 21:45 UTC by NullVoxPopuli

Idk if this is correct, but I know that gql usage is similar:
```js
const query = gql`
 query stuff
`
```
so I copy-pasted that for glimmer, which looks like

```js
cost template = hbs`
  <glimmer-stuff />
  <html-like />
```
```

2021-02-28 22:27 UTC, theHamsta commented
Do you want to add the glimmer parser, too (`parsers.lua`)? You would also need to add glimmer highlights to make it work. Probably, you can copy most stuff from html (github.com/nvim-treesitter/playground is useful for that).

2021-02-28 22:42 UTC, NullVoxPopuli commented
Just added an attempt at the parser -- hopefully it works? I'm not quite set up to debug tree-sitter itself quite yet.

Also, is there a way to upstream this sort of stuff to tree-sitter? shouldn't tree-sitter has these types of configs? rather than nvim-treesitter? (cause then every editor plugin needs the same customizations?)

2021-02-28 22:50 UTC, theHamsta commented
@NullVoxPopuli every editor (Atom, Neovim, Emacs) that uses tree-sitter has currently it's own queries they all highlight different things and have different queries implemented. Maybe we will have some Atom-style query fallback at some time but not at the moment. Neovim and Emacs basically forked because the tree-sitter ones very too basic and didn't map well to the editor's highlight groups.

2021-02-28 23:13 UTC, theHamsta commented
> Just added an attempt at the parser -- hopefully it works? 

You can test it with https://github.com/nvim-treesitter/playground

2021-02-28 23:18 UTC, NullVoxPopuli commented
I mean, the parser works, the stuff in question is just what's in _this_ PR, #985

2021-02-28 23:32 UTC, theHamsta approved these changes

2021-02-28 23:37 UTC, theHamsta commented on lua/nvim-treesitter/parsers.lua
> +    files = { "src/parser.c", "src/scanner.c" },
```lua
    branch = 'main',
```
does not work without setting the branch to main

2021-02-28 23:37 UTC, theHamsta commented on lua/nvim-treesitter/parsers.lua
> +    files = { "src/parser.c", "src/scanner.c" },
```lua
    branch = 'main',
```
does not work without setting the branch to main

2021-02-28 23:38 UTC, theHamsta requested changes
Branch needs to be set to `main`

2021-02-28 23:39 UTC, theHamsta commented
Seems to work
![image](https://user-images.githubusercontent.com/7189118/109437714-a0336200-7a26-11eb-8e18-151e43f5a1c8.png)

2021-02-28 23:40 UTC, NullVoxPopuli commented
> Branch needs to be set to main

I don't see that as an option?
![image](https://user-images.githubusercontent.com/199018/109437741-76614780-79f4-11eb-82b8-16349ad8d027.png)

2021-02-28 23:41 UTC, NullVoxPopuli commented
oh! you mean on the parser plugin, gotchya :+1:

2021-02-28 23:42 UTC, theHamsta approved these changes

2021-02-28 23:43 UTC, theHamsta commented
Ready to merge? Or do you want some highlights?

2021-02-28 23:46 UTC, theHamsta commented
```
 Tags that start with a lower case letter are HTML tags
((tag_name) @tag
  (#match? @tag "^[a-z]"))
; Tags that start with a capital letter are Glimmer components
((tag_name) @constructor
  (#match? @constructor "^[A-Z]"))

(attribute_name) @property

(string_literal) @string
(number_literal) @number
(boolean_literal) @boolean

; == Mustache Statements ===

; Hightlight the whole statement, to color brackets and separators
(mustache_statement) @tag

; Generic identifiers are variables
(identifier) @variable
; Helpers are functions
(helper_identifier) @function

(comment_statement) @comment

(attribute_node "=" @operator)

(block_params "as" @keyword)
(block_params "|" @operator)

[
  "<"
  ">"
  "</"
  "/>"
] @tag
```

2021-02-28 23:46 UTC, NullVoxPopuli commented
> Ready to merge or do you want some highlights? You can probably adapt the queries from their repo and use the tags from our html or other template languages.

I have highlights already with my manual / local config: 
![image](https://user-images.githubusercontent.com/199018/109437838-29ca3c00-79f5-11eb-95a9-e09ecaa13f9c.png)

![image](https://user-images.githubusercontent.com/199018/109437850-3cdd0c00-79f5-11eb-85c7-e5bb6634f93d.png)

How would highlights be added to nvim-treesitter?

2021-02-28 23:49 UTC, theHamsta commented
Just create a file `queries/glimmer/highlights.scm`. I made above some changes `tag.delimiter` -> `tag`. `attribute` -> `property`. Feel free to add more highlights if necessary (with tags documented in `CONTRIBUTING.md`).

2021-02-28 23:51 UTC, theHamsta commented
@NullVoxPopuli oops. We have `tag.delimiter`. Then, only `attribute` -> `property` as in Html. Now I understand what this `attribute` was that we removed.

2021-03-01 00:01 UTC, theHamsta commented
Thanks for this contribution! Maybe we need to add an auto-import feature for the highlight files...

2021-03-01 00:02 UTC, merged

2021-03-01 00:16 UTC, NullVoxPopuli commented
legit!

Now I have hbs highlighting in js/ts/hbs! (without configuring local repo references)

![image](https://user-images.githubusercontent.com/199018/109438805-7e6fb600-79f9-11eb-9925-85b9468ffb15.png)

2021-03-01 00:17 UTC, NullVoxPopuli commented
@alexlafroscia ^^ :D

2021-03-01 16:24 UTC, alexlafroscia commented
Sweet! Thanks for doing this @NullVoxPopuli -- I was going to wait until I had put it through it's paces more, but I'll up-stream fixes/improvements as they get made to the parser on my end.